name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: install jupyter-book
      run: pip install jupyter-book

    - name: build book
      run: jupyter-book build .

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html